    export type AllCardsType = {
        card: string,
        rank: number
    }

    export const ANSWER = [
        [
            {answer: "S:8~9人", rank: 1, color: "#000056", fontColor: "white"},
            {answer: "A:8~9人", rank: 2, color: "#d91326", fontColor: "white"},
        ],[
            {answer: "B:6~7人", rank: 3, color: "#ffcc33", fontColor: "black"},
            {answer: "C:4~5人", rank: 4, color: "#2e8b57", fontColor: "black"},
        ],[
            {answer: "D:3人", rank: 5, color: "#1e90ff", fontColor: "black"},
            {answer: "E:2人", rank: 6, color: "#ffffff", fontColor: "black"},
        ],[
            {answer: "F:FOLD", rank: 7, color: "#77787B", fontColor: "black"},
        ]
    ]

    export const AnswerRank = [
        {answer: "S:8~9人", rank: 1, color: "#000056", fontColor: "white"},
        {answer: "A:8~9人", rank: 2, color: "#d91326", fontColor: "white"},
        {answer: "B:6~7人", rank: 3, color: "#ffcc33", fontColor: "black"},
        {answer: "C:4~5人", rank: 4, color: "#2e8b57", fontColor: "black"},
        {answer: "D:3人", rank: 5, color: "#1e90ff", fontColor: "black"},
        {answer: "E:2人", rank: 6, color: "#ffffff", fontColor: "black"},
        {answer: "F:FOLD", rank: 7, color: "#77787B", fontColor: "black"},
    ];

    const ALLCARDS: AllCardsType[] =[
        {card :"A A", rank :1},
        {card :"A 2s", rank :4},
        {card :"A 2o", rank :7},
        {card :"A 3s", rank :4},
        {card :"A 3o", rank :7},
        {card :"A 4s", rank :4},
        {card :"A 4o", rank :7},
        {card :"A 5s", rank :4},
        {card :"A 5o", rank :7},
        {card :"A 6s", rank :4},
        {card :"A 6o", rank :7},
        {card :"A 7s", rank :4},
        {card :"A 7o", rank :6},
        {card :"A 8s", rank :4},
        {card :"A 8o", rank :6},
        {card :"A 9s", rank :4},
        {card :"A 9o", rank :5},
        {card :"A 10s", rank :2},
        {card :"A 10o", rank :4},
        {card :"A Js", rank :2},
        {card :"A Jo", rank :4},
        {card :"A Qs", rank :2},
        {card :"A Qo", rank :2},
        {card :"A Ks", rank :1},
        {card :"A Ko", rank :1},
        {card :"2 2", rank :5},
        {card :"2 3s", rank :7},
        {card :"2 3o", rank :7},
        {card :"2 4s", rank :7},
        {card :"2 4o", rank :7},
        {card :"2 5s", rank :7},
        {card :"2 5o", rank :7},
        {card :"2 6s", rank :7},
        {card :"2 6o", rank :7},
        {card :"2 7s", rank :7},
        {card :"2 7o", rank :7},
        {card :"2 8s", rank :7},
        {card :"2 8o", rank :7},
        {card :"2 9s", rank :7},
        {card :"2 9o", rank :7},
        {card :"2 10s", rank :7},
        {card :"2 10o", rank :7},
        {card :"2 Js", rank :7},
        {card :"2 Jo", rank :7},
        {card :"2 Qs", rank :7},
        {card :"2 Qo", rank :7},
        {card :"2 Ks", rank :6},
        {card :"2 Ko", rank :7},
        {card :"3 3", rank :5},
        {card :"3 4s", rank :7},
        {card :"3 4o", rank :7},
        {card :"3 5s", rank :7},
        {card :"3 5o", rank :7},
        {card :"3 6s", rank :7},
        {card :"3 6o", rank :7},
        {card :"3 7s", rank :7},
        {card :"3 7o", rank :7},
        {card :"3 8s", rank :7},
        {card :"3 8o", rank :7},
        {card :"3 9s", rank :7},
        {card :"3 9o", rank :7},
        {card :"3 10s", rank :7},
        {card :"3 10o", rank :7},
        {card :"3 Js", rank :7},
        {card :"3 Jo", rank :7},
        {card :"3 Qs", rank :7},
        {card :"3 Qo", rank :7},
        {card :"3 Ks", rank :6},
        {card :"3 Ko", rank :7},
        {card :"4 4", rank :5},
        {card :"4 5s", rank :7},//アンティ
        {card :"4 5o", rank :7},
        {card :"4 6s", rank :7},//アンティ
        {card :"4 6o", rank :7},
        {card :"4 7s", rank :7},
        {card :"4 7o", rank :7},
        {card :"4 8s", rank :7},
        {card :"4 8o", rank :7},
        {card :"4 9s", rank :7},
        {card :"4 9o", rank :7},
        {card :"4 10s", rank :7},
        {card :"4 10o", rank :7},
        {card :"4 Js", rank :7},
        {card :"4 Jo", rank :7},
        {card :"4 Qs", rank :7},//antie
        {card :"4 Qo", rank :7},
        {card :"4 Ks", rank :6},
        {card :"4 Ko", rank :7},
        {card :"5 5", rank :4},
        {card :"5 6s", rank :6},
        {card :"5 6o", rank :7},
        {card :"5 7s", rank :7},//antie
        {card :"5 7o", rank :7},
        {card :"5 8s", rank :7},
        {card :"5 8o", rank :7},
        {card :"5 9s", rank :7},
        {card :"5 9o", rank :7},
        {card :"5 10s", rank :7},
        {card :"5 10o", rank :7},
        {card :"5 Js", rank :7},
        {card :"5 Jo", rank :7},
        {card :"5 Qs", rank :7},//antie
        {card :"5 Qo", rank :7},
        {card :"5 Ks", rank :6},
        {card :"5 Ko", rank :7},
        {card :"6 6", rank :4},
        {card :"6 7s", rank :6},
        {card :"6 7o", rank :7},
        {card :"6 8s", rank :7},//antie
        {card :"6 8o", rank :7},
        {card :"6 9s", rank :7},//antie
        {card :"6 9o", rank :7},
        {card :"6 10s", rank :7},
        {card :"6 10o", rank :7},
        {card :"6 Js", rank :7},
        {card :"6 Jo", rank :7},
        {card :"6 Qs", rank :6},
        {card :"6 Qo", rank :7},
        {card :"6 Ks", rank :6},
        {card :"6 Ko", rank :7},
        {card :"7 7", rank :3},
        {card :"7 8s", rank :6},
        {card :"7 8o", rank :7},
        {card :"7 9s", rank :6},
        {card :"7 9o", rank :7},
        {card :"7 10s", rank :7},//antie
        {card :"7 10o", rank :7},
        {card :"7 Js", rank :6},
        {card :"7 Jo", rank :7},
        {card :"7 Qs", rank :6},
        {card :"7 Qo", rank :7},
        {card :"7 Ks", rank :6},
        {card :"7 Ko", rank :7},
        {card :"8 8", rank :3},
        {card :"8 9s", rank :5},
        {card :"8 9o", rank :7},
        {card :"8 10s", rank :5},
        {card :"8 10o", rank :7},
        {card :"8 Js", rank :6},
        {card :"8 Jo", rank :7},
        {card :"8 Qs", rank :6},
        {card :"8 Qo", rank :7},
        {card :"8 Ks", rank :6},
        {card :"8 Ko", rank :7},
        {card :"9 9", rank :2},
        {card :"9 10s", rank :4},
        {card :"9 10o", rank :6},
        {card :"9 Js", rank :5},
        {card :"9 Jo", rank :6},
        {card :"9 Qs", rank :5},
        {card :"9 Qo", rank :6},
        {card :"9 Ks", rank :4},
        {card :"9 Ko", rank :6},
        {card :"10 10", rank :2},
        {card :"10 Js", rank :3},
        {card :"10 Jo", rank :5},
        {card :"10 Qs", rank :4},
        {card :"10 Qo", rank :6},
        {card :"10 Ks", rank :3},
        {card :"10 Ko", rank :4},
        {card :"J J", rank :2},
        {card :"J Qs", rank :3},
        {card :"J Qo", rank :5},
        {card :"J Ks", rank :3},
        {card :"J Ko", rank :4},
        {card :"Q Q", rank :1},
        {card :"Q Ks", rank :1},
        {card :"Q Ko", rank :1},
        {card :"K K", rank :1},
    ];

    export default ALLCARDS;